#!/bin/bash
#
# You may face issue: Bash: mail: command not found
# to install mail command type this:
# sudo apt-get install mailutils
#
crontab -l > track_file
echo "0 0 * * * \
	md5_1=\"\$(md5sum /etc/crontab | awk '{ print \$1 }')\" && \
	md5_2=\"\$(cat /etc/crontab.log)\" && \
	if [ '\$md5_1' != '\$md5_2' ] ; \
	then \
		md5sum /etc/crontab | awk '{ print \$1 }' > /etc/crontab.log && \
		echo '/etc/crontab has been modified in last 24h' | \
		mail -s 'Alert, /etc/crontab eddited' root ; \
	fi" >> track_file
crontab track_file
rm track_file
